{% set version = "0.0.1" %}

package:
  name: gymnasium-notices
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/gymnasium-notices/gymnasium-notices-{{ version }}.tar.gz
  sha256: 3e8c868046f56dea84c949cc7e97383cccfab27152fc3f4968754e4c9c087ab9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=42
  run:
    - python >={{ python_min }}

test:
  imports:
    - gymnasium_notices
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Farama-Foundation/gym-notices
  summary: Notices for gymnasium
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
    - conda-forge/gymnasium
